### ISSUE TITLE
Error when installing from pip

### ISSUE THREAD

**Issue by vb-03** [pretix/pretix-adyen#13]
Hi,
When using Docker, the image building process throws this error with adyen:
```
=> ERROR [4/5] RUN pip3 install pretix-adyen                                                                                                         1.4s
------
 > [4/5] RUN pip3 install pretix-adyen:
#0 0.892 Collecting pretix-adyen
#0 0.962   Downloading pretix_adyen-1.3.1-py3-none-any.whl (54 kB)
#0 0.975      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.8/54.8 kB 5.3 MB/s eta 0:00:00
#0 1.008 Collecting Adyen==6.0.* (from pretix-adyen)
#0 1.024   Downloading Adyen-6.0.0.tar.gz (14 kB)
#0 1.034   Preparing metadata (setup.py): started
#0 1.201   Preparing metadata (setup.py): finished with status 'error'
#0 1.208   error: subprocess-exited-with-error
#0 1.208
#0 1.208   × python setup.py egg_info did not run successfully.
#0 1.208   │ exit code: 1
#0 1.208   ╰─> [86 lines of output]
#0 1.208       /usr/local/lib/python3.11/site-packages/setuptools/dist.py:755: SetuptoolsDeprecationWarning: Invalid dash-separated options
#0 1.208       !!
#0 1.208
#0 1.208               ********************************************************************************
#0 1.208               Usage of dash-separated 'description-file' will not be supported in future
#0 1.208               versions. Please use the underscore name 'description_file' instead.
#0 1.208
#0 1.208               By 2023-Sep-26, you need to update your project and remove deprecated calls
#0 1.208               or your builds will no longer be supported.
#0 1.208
#0 1.208               See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
#0 1.208               ********************************************************************************
#0 1.208
#0 1.208       !!
#0 1.208         opt = self.warn_dash_deprecation(opt, section)
#0 1.208       running egg_info
#0 1.208       creating /tmp/pip-pip-egg-info-1if3nazk/Adyen.egg-info
#0 1.208       writing /tmp/pip-pip-egg-info-1if3nazk/Adyen.egg-info/PKG-INFO
#0 1.208       writing dependency_links to /tmp/pip-pip-egg-info-1if3nazk/Adyen.egg-info/dependency_links.txt
#0 1.208       writing top-level names to /tmp/pip-pip-egg-info-1if3nazk/Adyen.egg-info/top_level.txt
#0 1.208       writing manifest file '/tmp/pip-pip-egg-info-1if3nazk/Adyen.egg-info/SOURCES.txt'
#0 1.208       Traceback (most recent call last):
#0 1.208         File "<string>", line 2, in <module>
#0 1.208         File "<pip-setuptools-caller>", line 34, in <module>
#0 1.208         File "/tmp/pip-install-ffkrf7lt/adyen_dad8a2770c2c4631b35d83e277a8b69e/setup.py", line 3, in <module>
#0 1.208           setup(
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
#0 1.208           return distutils.core.setup(**attrs)
#0 1.208                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 1.208           return run_commands(dist)
#0 1.208                  ^^^^^^^^^^^^^^^^^^
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 1.208           dist.run_commands()
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#0 1.208           self.run_command(cmd)
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
#0 1.208           super().run_command(command)
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 1.208           cmd_obj.run()
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 317, in run
#0 1.208           self.find_sources()
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 325, in find_sources
#0 1.208           mm.run()
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 573, in run
#0 1.208           self.add_defaults()
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 611, in add_defaults
#0 1.208           sdist.add_defaults(self)
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
#0 1.208           super().add_defaults()
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 249, in add_defaults
#0 1.208           self._add_defaults_python()
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/command/sdist.py", line 117, in _add_defaults_python
#0 1.208           build_py = self.get_finalized_command('build_py')
#0 1.208                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
#0 1.208           cmd_obj.ensure_finalized()
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
#0 1.208           self.finalize_options()
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/command/build_py.py", line 36, in finalize_options
#0 1.208           orig.build_py.finalize_options(self)
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build_py.py", line 46, in finalize_options
#0 1.208           self.set_undefined_options(
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 292, in set_undefined_options
#0 1.208           src_cmd_obj = self.distribution.get_command_obj(src_cmd)
#0 1.208                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
#0 1.208           klass = self.get_command_class(command)
#0 1.208                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 1.208         File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in get_command_class
#0 1.208           self.cmdclass[command] = cmdclass = ep.load()
#0 1.208                                               ^^^^^^^^^
#0 1.208         File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
#0 1.208           module = import_module(match.group('module'))
#0 1.208                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 1.208         File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
#0 1.208           return _bootstrap._gcd_import(name[level:], package, level)
#0 1.208                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 1.208         File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
#0 1.208         File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
#0 1.208         File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
#0 1.208         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
#0 1.208         File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
#0 1.208         File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
#0 1.208         File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
#0 1.208       ModuleNotFoundError: No module named 'pretix_plugin_build'
#0 1.208       [end of output]
#0 1.208
#0 1.208   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 1.209 error: metadata-generation-failed
#0 1.209
#0 1.209 × Encountered error while generating package metadata.
#0 1.209 ╰─> See above for output.
#0 1.209
#0 1.209 note: This is an issue with the package mentioned above, not pip.
#0 1.209 hint: See above for details.
```

**Comment by raphaelm** [comment]
Hey, which pip version are you using?

**Comment by vb-03** [comment]
`pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`

**Comment by raphaelm** [comment]
Please retry with pretix version 4.20.1 and reopen this if it still occurs!
